server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/backend
    username: developer
    password: developer

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
        order_inserts: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
parking:
  config:
    jwt:
      durationMilis: 5000000
      secretKey: "84d5d51368ba70d7e83db84fd27e54d6821364e8133b24887976ac69821a646f"